### ISSUE TITLE
Need Logo

### ISSUE THREAD

**Issue by madmartian5** [liberation-online/BOUNTY#1]
We need a logo designed.

**Comment by ggcarlosr** [comment]
What a friend, I think I can help you, could you give me some exact description of your repo or app, any idea you have in mind of how you want your logo you can send them to elwu3y@gmail.com

**Comment by madmartian5** [comment]
@ggcarlosr - the logo should be simple and capture the idea of a bounty. A bounty is an amount of money or other reward offered by an organization for a specific task done by a person. In our case the reward paid in Crypto. I have attached a small screencapture to show where the logo would be primarily used.

![screen shot 2018-05-14 at 4 09 29 pm](https://user-images.githubusercontent.com/28491705/40080723-22533bbc-588c-11e8-832d-62117a066170.png)

So probably something that has the word "Bounty" and a smaller icon - money bag for example.

**Comment by ggcarlosr** [comment]
That such brother here something of what I'm taking, if you see that it requires some change let me know, Color or element that is missing

![capture](https://user-images.githubusercontent.com/37964430/40213235-68fcff20-5a22-11e8-94d7-90ff701be45c.png)

**Comment by madmartian5** [comment]
**Looking good**, and I know everyone has a different idea when it comes to colour. But for me, I think maybe the grey is a bit light and the blue isn't quite working for me. I wonder if you could do a few different variations and we can ask our discord communitiy which they prefer?

**Comment by ggcarlosr** [comment]
Perfect, @amexperts  I think your suggestion right here I leave 2 colors which any of them would go very well with the theme of your project, notify me if you like it or have a specific color that catches your attention which we can use. 

![bounty02](https://user-images.githubusercontent.com/37964430/40272105-fd2bfde6-5b75-11e8-85b3-04185d179df9.png)

![bounty01](https://user-images.githubusercontent.com/37964430/40272104-fcf56c22-5b75-11e8-8e89-347f58670640.png)

**Comment by madmartian5** [comment]
Getting good feedback. Just a question on whether we could see an example using colour from the KIWI logo - you can see here: http://www.thekiwi.online/

**Comment by ggcarlosr** [comment]
ok friend taking your suggestions into consideration I leave new changes and added elements according to what I suggest.

![bounty03](https://user-images.githubusercontent.com/37964430/40282257-9fe59ff0-5c3a-11e8-826e-fd415470cf1f.png)
![bounty01](https://user-images.githubusercontent.com/37964430/40282259-a057ddfe-5c3a-11e8-95b0-700b5b465b75.png)
![bounty02](https://user-images.githubusercontent.com/37964430/40282260-a0f70294-5c3a-11e8-97fc-cb7cd4390077.png)

**Comment by madmartian5** [comment]
The green is great. Could we see the bottom one with the following variations.. Will send you some KIWI when we make final decision :)

1. "Platform" in grey
2. the text not slanted.

Thank you very much.

**Comment by ggcarlosr** [comment]
**# Option 1** 
![bounty01](https://user-images.githubusercontent.com/37964430/40322723-49ab5b80-5d01-11e8-82cf-752cd052a41f.png)

**# Option 2** 
![bounty02](https://user-images.githubusercontent.com/37964430/40322726-4a0f2926-5d01-11e8-95a2-e2aa80052b34.png)




**# Option 1 or Option 2?**

**Comment by madmartian5** [comment]
Ok. thanks for your patience.. So now, I have made a decision to go with this one :)

![screen shot 2018-05-22 at 12 40 11 am](https://user-images.githubusercontent.com/28491705/40333418-afb4fe98-5d58-11e8-865f-f320584aee89.png)

If you could send me an email to contact@thekiwi.online

**Comment by ggcarlosr** [comment]
ok friend will create a request for removal on github, with the editable files you think? and additional I will send the compressed files to the indicated mail.

**Comment by madmartian5** [comment]
Perfect. Thanks
